osa/courses/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<course_id>[0-9]+)/$', views.detail, name='detail'),
]

osa/osa/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^specializations/', include('specializations.urls',
                                      namespace="specializations")),
    url(r'^terms/', include('terms.urls', namespace="terms")),
    url(r'^admin/', include(admin.site.urls)),
]

osa/specializations/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<specialization_id>[0-9]+)/$', views.detail, name='detail'),
]

osa/students/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<student_id>[0-9]+)/$', views.detail, name='detail'),
]

osa/terms/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<term_id>[0-9]+)/$', views.detail, name='detail'),
]

osa/courses/models.py
from django.db import models


class Course(models.Model):
    code = models.CharField(max_length=10)
    name = models.CharField(max_length=255)
    hours = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.code + ": " + self.name

osa/specializations/models.py
from django.db import models


class Specialization(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

osa/students/models.py
from django.db import models


class Student(models.Model):
    display_name = models.CharField(max_length=50)

    def __str__(self):
        return self.display_name

osa/terms/models.py
from django.db import models


class Term(models.Model):
    NAME_CHOICES = (
        ('S', 'SPRING'),
        ('M', 'SUMMER'),
        ('F', 'FALL'),
    )
    name = models.CharField(max_length=1, choices=NAME_CHOICES)
    year = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.NAME_CHOICES[self.name] + str(self.year)

osa/courses/views.py
from django.shortcuts import get_object_or_404, render

from .models import Course


def index(request):
    latest_courses = Course.objects.all()
    context = {'latest_courses': latest_courses}
    return render(request, 'courses/index.html', context)


def detail(request, course_id):
    latest_courses = Course.objects.all()
    course = get_object_or_404(Course, pk=course_id)
    context = {'latest_courses': latest_courses, 'course': course}
    return render(request, 'courses/detail.html', context)

osa/osa/views.py
from django.views.generic.base import TemplateView


class HomeView(TemplateView):
    template_name = 'index.html'

osa/specializations/views.py
from django.shortcuts import get_object_or_404, render

from .models import Specialization


def index(request):
    latest_specializations = Specialization.objects.all()
    context = {'latest_specializations': latest_specializations}
    return render(request, 'specializations/index.html', context)


def detail(request, specialization_id):
    latest_specializations = Specialization.objects.all()
    specialization = get_object_or_404(Specialization, pk=specialization_id)
    context = {'latest_specializations': latest_specializations,
               'specialization': specialization}
    return render(request, 'specializations/detail.html', context)

osa/students/views.py
from django.shortcuts import get_object_or_404, render

from .models import Student


def index(request):
    latest_students = Student.objects.all()
    context = {'latest_students': latest_students}
    return render(request, 'students/index.html', context)


def detail(request, student_id):
    latest_students = Student.objects.all()
    student = get_object_or_404(Student, pk=student_id)
    context = {'latest_students': latest_students, 'student': student}
    return render(request, 'students/detail.html', context)

osa/terms/views.py
from django.shortcuts import get_object_or_404, render

from .models import Term


def index(request):
    latest_terms = Term.objects.all()
    context = {'latest_terms': latest_terms}
    return render(request, 'terms/index.html', context)


def detail(request, term_id):
    latest_terms = Term.objects.all()
    term = get_object_or_404(Term, pk=term_id)
    context = {'latest_terms': latest_terms, 'term': term}
    return render(request, 'terms/detail.html', context)

osa/courses/templates/courses/detail.html
{% extends courses/index.html' %}

{% block page_title %}
    <title>OSA | Courses | {{ course.name }}</title>
{% endblock page_title %}

{% block content %}
<h1>{{ course.name }}</h1>
<p>{{ course.hours }}</p>
{% endblock content %}

osa/courses/templates/courses/index.html
{% extends 'base.html' %}

{% block page_title %}
    <title>OSA | Courses</title>
{% endblock page_title %}

{% block sidebar %}
{% if latest_courses %}
<ul>
  {% for course in latest_courses %}
      <li><a href="{% url 'courses:detail' course.id %}">{{ course.name }}</a></li>
  {% endfor %}    
</ul>
{% else %}
  <p>No courses are available.</p>
{% endif %}
{% endblock sidebar %}

{% block content %}
<p>This is the courses home.</p>
{% endblock content %}

osa/specializations/templates/specializations/detail.html
{% extends 'specializations/index.html' %}

{% block page_title %}
    <title>OSA | Specializations | {{ specialization.name }}</title>
{% endblock page_title %}

{% block content %}
<h1>{{ specialization.name }}</h1>
{% endblock content %}

osa/specializations/templates/specializations/index.html
{% extends 'base.html' %}

{% block page_title %}
    <title>OSA | Specializations</title>
{% endblock page_title %}

{% block sidebar %}
{% if latest_specializations %}
<ul>
  {% for specialization in latest_specializations %}
      <li><a href="{% url 'specializations:detail' specialization.id %}">{{ specialization.name }}</a></li>
  {% endfor %}    
</ul>
{% else %}
  <p>No specializations are available.</p>
{% endif %}
{% endblock sidebar %}

{% block content %}
<p>This is the specializations home.</p>
{% endblock content %}

osa/students/templates/students/detail.html
{% extends 'students/index.html' %}

{% block page_title %}
    <title>OSA | Students | {{ student.display_name }}</title>
{% endblock page_title %}

{% block content %}
<h1>{{ student.display_name }}</h1>
{% endblock content %}

osa/students/templates/students/index.html
{% extends 'base.html' %}

{% block page_title %}
    <title>OSA | Students</title>
{% endblock page_title %}

{% block sidebar %}
{% if latest_students %}
<ul>
  {% for student in latest_students %}
      <li><a href="{% url 'students:detail' student.id %}">{{ student.display_name }}</a></li>
  {% endfor %}    
</ul>
{% else %}
  <p>No students are available.</p>
{% endif %}
{% endblock sidebar %}

{% block content %}
<p>This is the students home.</p>
{% endblock content %}

osa/templates/base.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    {% block page_title %}
        <title>OSA | Home</title>
    {% endblock page_title %}
    <link rel="stylesheet" href="{% static "css/foundation.css" %}"/>
    <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
    <script src="{% static "js/vendor/modernizr.js" %}"></script>
    <link rel="stylesheet" href="{% static "css/app.css" %}">
</head>
<body>
<div class="row">
    <div class="large-3 columns">
        <h1><a href="{% url 'home' %}"><span class="logo">GT</span><span class="logo-emp">OSA</span></a></h1>
    </div>
    <div class="large-9 columns">
        <ul class="inline-list right">
            <li><a href="{% url 'courses:index' %}">Courses</a></li>
            <li><a href="{% url 'specializations:index' %}">Specializations</a></li>
            <li><a href="{% url 'students:index' %}">Students</a></li>
            <li><a href="{% url 'terms:index' %}">Terms</a></li>
        </ul>
    </div>
</div>
<div class="row">

    <div class="large-9 push-3 columns">
        {% block content %}
            <h3>Page Title
                <small>Page subtitle</small>
            </h3>

            <p>Bacon ipsum dolor sit amet salami ham hock biltong ball tip drumstick sirloin pancetta meatball short
                loin. Venison tail chuck pork chop, andouille ball tip beef ribs flank boudin bacon. Salami andouille
                pork belly short ribs flank cow. Salami sirloin turkey kielbasa. Sausage venison pork loin leberkas
                chuck short loin, cow ham prosciutto pastrami jowl. Ham hock jerky tri-tip, fatback hamburger shoulder
                swine pancetta ground round. Tri-tip prosciutto meatball turkey, brisket spare ribs shankle chuck cow
                chicken ham hock boudin meatloaf jowl.</p>

            <p>Ground round pastrami pork loin tenderloin jerky. Jerky spare ribs biltong, ham hock ham capicola pork.
                Jerky turducken pork, meatloaf sausage capicola swine corned beef turkey short loin. Tongue prosciutto
                pork loin, ground round spare ribs venison kielbasa strip steak.</p>

            <p>Hamburger bresaola turkey t-bone, leberkas salami pork chop ham hock beef ribs. Rump biltong meatball
                venison, short ribs pork loin shank shankle corned beef beef. Cow salami jowl short loin hamburger
                fatback. Short ribs pork belly shoulder pastrami drumstick salami corned beef ham hock bresaola. Swine
                filet mignon cow sausage ball tip. Cow ribeye ground round, sausage pork loin pig beef ball tip turkey
                boudin.</p>

            <p>Prosciutto ball tip filet mignon andouille frankfurter chicken rump sausage meatball. Filet mignon
                meatloaf ground round andouille ham hock pork. Bresaola short loin meatball chuck hamburger pig. Turkey
                venison chuck, tongue fatback tail swine jerky corned beef shank kielbasa prosciutto ribeye ham tri-tip.
                Rump bacon pork belly meatloaf shoulder short loin meatball kielbasa pork loin tongue bresaola brisket
                corned beef jowl prosciutto. Beef ribs shankle short ribs pork belly corned beef fatback pork chop
                tongue biltong boudin strip steak sirloin meatloaf pancetta.</p>

        {% endblock content %}
    </div>


    <div class="large-3 pull-9 columns">

        {% block sidebar %}
            <ul class="side-nav">
                <li><a href="#">Section 1</a></li>
                <li><a href="#">Section 2</a></li>
                <li><a href="#">Section 3</a></li>
            </ul>
        {% endblock sidebar %}

        <p><img src="http://placehold.it/320x240&text=Ad"/></p>

    </div>
</div>

<footer class="row">
    <div class="large-12 columns">
        <hr/>
        <div class="row">
            <div class="large-6 columns">
                <p>Some message</p>
            </div>
            <div class="large-6 columns">
                <ul class="inline-list right">
                    <li>menu1</li>
                    <li>menu2</li>
                    <li>menu3</li>
                </ul>
            </div>
        </div>
    </div>
</footer>

<script src="{% static "js/vendor/jquery.js" %}"></script>
<script src="{% static "js/foundation.min.js" %}"></script>
<script>
    $(document).foundation();
</script>
</body>
</html>

osa/templates/index.html
{% extends 'base.html' %}

{% block sidebar %}
<ul>
</ul>
{% endblock sidebar %}

osa/terms/templates/terms/detail.html
{% extends 'terms/index.html' %}

{% block page_title %}
    <title>OSA | Term | {{ term }}</title>
{% endblock page_title %}

{% block content %}
<h1>{{ term }}</h1>
<p>{{ term.code }}</p>
<p>{{ term.year }}</p>
{% endblock content %}

osa/terms/templates/terms/index.html
{% extends 'base.html' %}

{% block page_title %}
    <title>OSA | Term</title>
{% endblock page_title %}

{% block sidebar %}
{% if latest_terms %}
<ul>
  {% for term in latest_terms %}
      <li><a href="{% url 'terms:detail' term.id %}">{{ term }}</a></li>
  {% endfor %}    
</ul>
{% else %}
  <p>No terms are available.</p>
{% endif %}
{% endblock sidebar %}

{% block content %}
<p>This is the terms home.</p>
{% endblock content %}